version: '3.8'
# name: "webgui-Amplifier"
name: "${NAME_PROJECT}"
services:
  react-app:
    image: m65535/web-node:16-alpine
    container_name: "${NAME_APP}"
    working_dir: /app
    ports:
      - "${APP_PORT}:3000"
    volumes:
      # Монтируем только исходный код
      - ./src:/app/src
      - ./public:/app/public
      - ./build_scripts:/app/build_scripts
      - ./gulpfile.js:/app/gulpfile.js                    # Для скриптов сборки
      - ./.git:/app/.git                                  # Для скриптов сборки
      - ./version_build.json:/app/version_build.json      # Для скриптов сборки
      - ./build_arch:/app/build_arch                      # Для скриптов сборки итоговый скрипт       
      
      
      # - ./package.json:/app/package.json
      # node_modules из контейнера в локальную папку
      # - ./node_modules:/app/node_modules
    environment:
      - DISABLE_ESLINT_PLUGIN=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run start:docker  # Только запуск!
    stdin_open: true
    tty: true

  json-server:
    image: m65535/web-json-server:1.0.0-beta.3
    working_dir: /data/    
    ports:
      - "${JSON_PORT}:3001"
    volumes:
    # - ./json-server/data/BlockControl/db.json:/data/db.json
      - ${JSON_PATCH}:/data/db.json
      
    environment:
      - CHOKIDAR_USEPOLLING=true    
    command: json-server --watch db.json --host 0.0.0.0 --port 3001
